### ISSUE TITLE
Consider offset attributes on portal element

### ISSUE THREAD

**Issue by oliverdunk** [WICG/portals#109]
I was playing with portals, and created this basic setup for a blog:

![image](https://user-images.githubusercontent.com/6097064/57377053-5e726100-7199-11e9-9148-ca48b90c66d4.png)

Essentially, a single post shows on each post page. The home page then consists of a portal for each post (outlined in blue) that is used to display a preview of its content (in particular, the red section).

It would be great if I could easily use an attribute on the portal elements to shift the visible part of the page downwards. To create this, which I feel is a fairly simple use case for portals, I had to:

- Introduce negative margins (to scroll the page up)
- Set overflow to hidden to hide the scroll bars
- Register an event listener that removes these styles on portal activate

That seems like a lot of work, and it would be nice if there was a better option.

Side note: do we ever want scrollbars with portals? I wonder if they can just be hidden in all cases.

**Comment by jeremyroman** [comment]
Sure, opening an issue about scrollbars specifically sounds reasonable.

**Comment by domenic** [comment]
Given that we avoid adding presentational attributes to HTML, I think this is indeed best handled via CSS in the way @jeremyroman described. As such, I'll close this issue.
