### ISSUE TITLE
Consider pushing a URL onto the history stack rather than replacing

### ISSUE THREAD

**Issue by matthewp** [WICG/portals#116]
I have been experimenting with the API in Canary and I like it a lot. For my use case I would like to be able to do:

1. Click a link
2. Load the next page in a portal and animate it, then .activate().
3. . adoptPredecessor()
4. When the back button is clicked, animate the predecessor portal back into view and .activate()

There's a couple of reasons why this won't work at present:

1. When you .activate() the portaled page, it replaces the history rather than pushing a new item onto the stack.
2. There's no way to .pop() the last item.

**Comment by jeremyroman** [comment]
Thanks for the feedback. We definitely intend for the session history to work in a more reasonable way. Issue #19 is the best tracking issue for that (though our ongoing work is more active than activity on that issue would suggest).

**Comment by matthewp** [comment]
@jeremyroman Glad to hear it, I'll track that issue.

Side note, if we encounter bugs in the Canary implementation is it best to file that on Chromium or here (not sure if its a spec bug or implementation)?

**Comment by jeremyroman** [comment]
If it seems like an issue in the implementation (crashes being the most obvious example), the Chromium tracker is ideal. If it seems like it's a use case that isn't contemplated in the design or spec, then this tracker is ideal.

It's not a big deal if you end up filing in the wrong place; our team looks in both places.

**Comment by matthewp** [comment]
Ok, I see a flash when .activate() is called, I suspect that's an implementation bug so I'll try in the tracker. Thank you for your help!

**Comment by jeremyroman** [comment]
Yup, that's https://bugs.chromium.org/p/chromium/issues/detail?id=914102. :)
