### ISSUE TITLE
back button (e.g. location history)

### ISSUE THREAD

**Issue by localhostdotdev** [WICG/portals#117]
**steps to reproduce**

- go to https://uskay-portals-demo.glitch.me
- set portal to https://example.com
- click back button

**expected behavior**

goes back to https://uskay-portals-demo.glitch.me

**actual behavior**

doesn't go back anywhere (can't even click back button)

**system info**

chrome canary 76.0.3790.0 (not sure if a spec issue/implementation issue/non-issue?)

**Comment by matthewp** [comment]
This is covered in https://github.com/WICG/portals/issues/19

**Comment by jeremyroman** [comment]
Thanks for the feedback. Yup, this is a known issue. We're working on it.
