### ISSUE TITLE
Remove modal feature or split into second spec, just have it transition completely to sub page

### ISSUE THREAD

**Issue by natew** [WICG/portals#120]
The inlining feature (where it shows the portal as a modal), is bad for a few reasons:

1. **It's bad UX**: the user has a new concept to learn, and a new interaction, when there already exists interactions for going between pages. Adding modals also removes the incentive for browser to improve their existing UX. For example "swipe back" is amazing, fast and intuitive, it would be best to encourage browsers to continue to improve the existing, single-concept of a page. WebOS had some great ideas on how to make it smooth and fun, without needing some special nested concept.
2. **It adds a huge amount of weight to browser runtimes and UI**: Why would you introduce the first version of a spec with a lot of extra bloat. Start simple with a sub-page that transitions to a full page. If there is demand for "modal-style inline pages", then discuss it separately.
3. **It's extremely unfriendly to small companies**: modal-style portals will become a lock-in feature for large platforms. It will prevent competition and trap users into whichever existing platforms leverage them the most.
4. **It's not clearly a benefit in any way**: even not considering the above, I'm not sure at all why this would be considered a good idea.
5. **It's something that could be done in the browser level, without a spec**: If you have a portal spec implemented without modaling, any browser could experiment with their own UI. Perhaps they could use cards, a grid, etc. Enforcing a specific modal-style UI and interaction set is not necessary.

**Comment by oliverdunk** [comment]
I’m not certain that I understand your vision here - are you suggesting browsers implement new UI that shows two pages in a split screen view, with an API to enter that view and then enlarge one of them?

I have some thoughts on your arguments, but will save those until I know for certain your proposal 🙂

**Comment by natew** [comment]
Basically, I'm proposing to remove the modal feature that shows portals as a sub-view inside of a parent page. I think this feature is fundamentally bad for the web, as it will obviously cause platforms to never "let you leave".

The whole portal idea to me is quite dangerous. What it does is a little sinister. It basically sweet talks you into liking it with a small amount of slick interface sugar, and in exchange it sets up a world where all websites have an automatic bridge built into them that can speak between each other, passing unlimited data back to the referring website.

Further, and worse IMO, is the modal feature. Because then this actually gets into fully locking users into the "entry-points" of the web; ie, facebook, google. And the upside? A slightly, slightly, less cumbersome way to navigate "back" to a referring website. And what I'm arguing is, this "slightly, slightly less cumbersome" interface is actually something that you could come up with entirely inside the browser interface, without portals altogether. So in a way, the modal feature in portals I see as a false-justification: a way to make them seem necessary and desirable, when in fact it could be completely de-coupled (the visual modaling effect and the portal feature itself).

So, my argument would be: remove the modal aspect. It will entrench big platforms. And all the real benefits of portals (preloading, fast transitions) would remain.

**Comment by domenic** [comment]
Could you explain what "the modal feature" is? What part of the spec document (for which this a repo for) are you referring to?

**Comment by natew** [comment]
As shown in the explainer video, which was on the Google blog post I
believe recently talking about it.

Is there not an ability for the browser to show the page “above” the
previous page? Perhaps this is just the Chrome teams plan to implement, in
which case the general critique stands that this feature overall seems to
promote some bad incentives.

**Comment by natew** [comment]
Yea this video:

https://web.dev/hands-on-portals

In some cases it moves full page. In others it’s a pop up inside the
previous page (commonly known as a modal). This latter functionality is the
objection.

**Comment by rlamacraft** [comment]
I would suggest checking out the demo code and taking some time to understand exactly what it’s doing, specifically [ttt-controller.js](https://github.com/WICG/portals/blob/master/demos/portal-embed-demo/public/js/ttt/ttt-controller.js). You can see that the embedded site is offering to display the predecessor page in the background, but it is under no obligation to do so. It could provide just a back button, a contextual preview, or it could provide nothing at all - which is what happens now if you portal to any site on the web. 

There are definitely some concerns about changes to the fundamentals to the Web that this spec proposes ([as per this discussion](http://discourse.wicg.io/t/proposal-for-promotable-iframe/2375?page=2)), but I don’t believe this to be one of them.

**Comment by jeremyroman** [comment]
While we have done some thinking about modal activation as a possible feature in the future (one can imagine how UA mediation might be helpful in some cases), the current proposal and demos do not do this. Instead, they currently have the successor page creating that effect itself (by applying suitable CSS to the adopted previous page, as adopted in a `<portal>`).

Since we can't currently remove the modal feature from the spec (it isn't there), I'm going to close this issue, but we do appreciate the feedback.
