### ISSUE TITLE
Possible vulnerabilities

### ISSUE THREAD

**Issue by useretail** [WICG/portals#122]
Your new portal tag is nothing more than an attempt to integrate more ads into peoples browsers.
As a side effect you are going to create a lot security problems. They will be reported in this thread.

**Comment by KenjiBaheux** [comment]
Please file separate issues for the security problems that you may identify.
Also, kindly review the w3c's [code of conduct](https://www.w3.org/Consortium/cepc/).

**Comment by useretail** [comment]
Thank you. You just confirmed my theory.

**Comment by useretail** [comment]
Also confirmed by the media today: https://www.theverge.com/2019/5/14/18623541/google-gallery-discovery-mobile-ads-announced
