### ISSUE TITLE
Problem with <portal> tag

### ISSUE THREAD

**Issue by Moonlightcat76** [WICG/portals#124]
Hello Community. I am very sorry for my poor English language. Please help me, because i don't find answer on Russian language sites.

I try to use < portal > < /portal > tag as iframe. I downloaded new Ghrome Beta browser and enable portal function in settings.

I try to use this code, the same as iframe.

--------------------------------------------------------------------------
portal {    
    width: 100%;
    height: 100%;
}

< portal src="https://testurl.com"  > <  /portal  >
--------------------------------------------------------------------------------

https://testurl.com - loaded without problem. But mouse don't
work, all links non-clickable.  I try differen sites as testurl,  all the same. 

I think i made mistake in code. But where? I try to read google documents but English language and are lot technical terms is very difficult for me. I am oldtimer and not IT-guy.

I will apreciate if you help me. Sorry again for my  English.

Thanks-in-advance

**Comment by matthewp** [comment]
Not sure if this helps but you need Canary and to enable the flag.

**Comment by jeremyroman** [comment]
The spec is currently vague about this, but currently we do not accept input to a portal when it is not activated. In the future we will probably add a mode that does accept input.
