### ISSUE TITLE
Allow creation of the portal's browsing context when the src attribute is set

### ISSUE THREAD

**Issue by lucasgadani** [WICG/portals#137]
Whenever the src attribute is set, if the guest browsing context is null, we abort the steps. We should consider creating the portal browsing context when the src attribute is set, whenever the element is browsing-context connected.

**Comment by jeremyroman** [comment]
Yeah, I think my intuition is that the right approach is something like:

Whenever the src is set (to a valid non-empty URL) or the element becomes BC-connected, make a BC if none yet exists and navigate it to that URL.

That implies that making a `<portal>` with no src BC-connected will not open a new BC group (yet), and that setting the src of a `<portal>` that has lost its BC (by going to an invalid place, by activating, etc) may also create the BC group.

**Comment by lucasgadani** [comment]
There's also another subtle issue: adopting the predecessor changes the state of the predecessor from orphaned to portal. That means it won't be closed in step 5.13 of the "activate a portal browsing context" algorithm, in the case where the element wasn't inserted.
