### ISSUE TITLE
URL scheme control on 'set the source URL' may be insufficient

### ISSUE THREAD

**Issue by jeremyroman** [WICG/portals#145]
Based on feedback from @annevk.

It's not clear that this control prevents navigation to data: URLs and other things that we might wish to avoid (e.g. due to an HTTP redirect).

A quick glance suggests that at least that case might be fine (https://html.spec.whatwg.org/multipage/browsing-the-web.html#process-a-navigate-fetch doesn't seem to follow redirects to URLs except with an HTTP(S) scheme, but there may be other tricks possible.

**Comment by annevk** [comment]
I don't think you're reading the algorithm correctly. Note that it instructs fetch to not follow redirects and handles them itself in steps 6-9.

**Comment by jeremyroman** [comment]
Ah, you're right. I missed it even after looking several times.

I saw "If response does not have a location URL or the location URL is not a URL whose scheme is an HTTP(S) scheme, then set done to true." and assumed that this prevented it from following the redirect, but the below steps handle the location URL rather than the response that included it. The algorithm being both iterative and recursive kinda confused me, but I think I get it now.
