### ISSUE TITLE
Should navigations in a portal context respect Content-Disposition?

### ISSUE THREAD

**Issue by jeremyroman** [WICG/portals#150]
Should it be possible to handle a response [as a download](https://html.spec.whatwg.org/multipage/links.html#as-a-download)? This might permit drive-by downloads, or at a minimum, user annoyance.

There might be legitimate reasons to want to allow this, but I'm not currently aware of them. Related to #145 which also involves hooks into navigate.

**Comment by jeremyroman** [comment]
For now, Chromium simply drops any downloads that would be initiated due to `Content-Disposition`, `<a download>`, etc.

**Comment by jakearchibald** [comment]
I think we should have an answer all the times we fork from iframe behaviour. If we're unsure, consistency seems like a good choice.

**Comment by jeremyroman** [comment]
For context, I believe iframes allow them by default (though I'd hope with a user gesture guard at least?), but sandboxed iframes don't as of [pretty recently](https://www.chromestatus.com/feature/5706745674465280).

**Comment by jakearchibald** [comment]
A gesture isn't required to set `location.href` to a URL that triggers a download. Calling `click()` on an `<a download>`… I think that works without a gesture.

**Comment by domenic** [comment]
My thinking (per #237) is that portaled content should not be allowed to cause downloads, in any fashion. (Pre-activation.)
