### ISSUE TITLE
File protocol support?

### ISSUE THREAD

**Issue by rharasim** [WICG/portals#160]
Hello, I am trying to use portal element with [electronjs](https://electronjs.org/) framework. But I face a problem with loading local files into portal element.

`Portals only allow navigation to protocols in the HTTP family.`

Is it possible to load local html files into portal element? If not, what are the reasons?

**Comment by domenic** [comment]
Portals only support HTTP(S) schemes, as those are the only well-defined ones on the web platform. file: URLs have various security issues (e.g. no well-defined origin), and as such are generally not supported by modern web platform features like JS modules, portals, fetch(), etc.
