### ISSUE TITLE
Keeping the mobile mode in the portal

### ISSUE THREAD

**Issue by juliadou** [WICG/portals#167]
I am usually emulating mobile mode when I open the chrome developer console under my desktop chrome. I notice the portal window ignores the window emulation mode and loads desktop site. Is there a way to make portal mode respect the hosting window mode (desktop or mobile)?

**Comment by jeremyroman** [comment]
This sounds like a Chromium implementation issue; this tracker is intended for issues with the feature design and specification. After verifying that it occurs on the latest canary release (this isn't a supported feature on Chrome stable at the moment), please file a bug on crbug.com. Thanks. :)

**Comment by juliadou** [comment]
Added a chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1032625
