### ISSUE TITLE
Can embedded content have portals?

### ISSUE THREAD

**Issue by ehsan-karamad** [WICG/portals#18]
My concern is specifically a scenario where a site embeds some third party content that uses portals:

``` HTML
 <iframe sandbox="allow-scripts" src="http://foo.com/contains_portal.html"></iframe>
```
What is the expected behavior if the the `<iframe>` adds and activates a portal to itself? Or perhaps opens a new window to itself which contains a portal and activates that. I could not figure out the behavior from the explainer. 

I am thinking:

1. Embedded contents cannot have portals (or it will be ignored).
2. Embedded contents can have portals
  2.1 An active portal navigates the parent
  2.2 An active portal navigates its container frame

I highly doubt 2.2. happening since the design for Chromium hints at use of WebContents for the portal. 2.2 then would be shipping a light version of Chromium's `<webview>` then.

**Comment by ehsan-karamad** [comment]
These perhaps might not be issues when `sandbox` propagates the same way as `window.open`. Although something such as `allow-top-navigation` should be respected.

I am not sure what the behavior for feature policy should be and if `<portal>` should have a notion of [_container_policy_](https://wicg.github.io/feature-policy/#container-policies).

**Comment by lucasgadani** [comment]
That's a good point, unless there's a use case in mind, I think we shouldn't let nested browsing contexts to have portals.

That said, even if we allow iframes to have portals, they shouldn't be able to navigate the parent. Portals won't be part of the frame tree, and if we are disowning the opener, that means they shouldn't have access to the parent WindowProxy.

**Comment by ehsan-karamad** [comment]
> I think we shouldn't let nested browsing contexts to have portals.
What do you think is the right behavior when that occurs:

1. Do not load the portal's content (silently ignore)
2. Or throw an error (with reason) perhaps?

**Comment by lucasgadani** [comment]
Yes, I propose throwing an error, similarly to violating an iframe's sandbox attributes.

**Comment by ehsan-karamad** [comment]
I guess the content of the `portal.src` should not be loaded at all (and then perhaps throw an error). The page itself (which is embedded inside `portal`) should not break.

**Comment by lucasgadani** [comment]
Yes, that's the intention.

**Comment by jeremyroman** [comment]
I suspect we will want to allow portals to contain portals, though, where activation takes over the containing portal view. If we encourage this use for rich navigation, I think people will naturally want to use it even for embedded content.

**Comment by ehsan-karamad** [comment]
> I suspect we will want to allow portals to contain portals, though, where activation takes over the containing portal view.

I wonder if this could potentially open door to other issues. With this, when the contents inside portal gets notified about activation, it would not mean it is a top-level activation and perhaps deprived of some of the permissions expected for top-level (e.g., not sure how we treat `sandbox` for `<portal>`).

I lean towards having `<portal>` activation conditioned on * embedder/parent browsing context* being top-level. Otherwise either queue activation or just fail immediately?

**Comment by jeremyroman** [comment]
Or we could have the PortalActivateEvent have a readonly attribute that indicates whether it has been activated in the top-level context? It just seems likely to me that portaled content is going to want seamless navigation within the portal sooner or later.

**Comment by domenic** [comment]
The current spec does not seem to disallow activating a portal inside an iframe, but I'm not sure that's been fully accounted for. For example, coming from #68, I noted that the predecessor BC is "closed". But, "close" is so far on the web only used for top-level BCs, not for nested BCs. There may be other inconsistencies or assumptions.

**Comment by jeremyroman** [comment]
It is presently impossible for a (non-inert) portal to exist inside an iframe, because we don't create a browsing context for it if it is. There's a note in the draft to this effect:

> In particular, this means a portal element loses its guest browsing context if it is moved to the active document of a nested browsing context.
> 
> Similarly, the steps when a portal element becomes browsing-context connected prevent elements from creating a new guest browsing context while inside such documents.
> 
> It is therefore impossible to embed a portal browsing context in a nested browsing context.

**Comment by domenic** [comment]
Ah, oops, I forgot that. OK, we might be fine then.

**Comment by domenic** [comment]
Closing since the spec seems to cover this. If we think there are use cases for nested portals or portals inside iframes, let's open a new issue focused on those use cases.
