### ISSUE TITLE
Consider removing the three-argument postMessage variant

### ISSUE THREAD

**Issue by domenic** [WICG/portals#205]
In general, the new design of using an options object is preferred, because it gives consistency across [all the different postMessage() API surfaces](https://gist.github.com/domenic/d0ea64893c255445574fd535ca89731f). Maybe we shouldn't introduce a new place with the three-argument variant.

Thoughts?

**Comment by a4sriniv** [comment]
If we take away cross-origin messaging, the targetOrigin parameter doesn't seem useful anymore. 
So I think we could omit targetOrigin and make the API look like all the other postMessage surfaces (except window postMessage).

**Comment by jeremyroman** [comment]
Yeah, I think we can remove it. If we ever allow some form of confined cross-origin messaging (e.g. between same-site origins, or some other cluster of origins), we could add this back in the options dictionary.

**Comment by domenic** [comment]
Ah, that makes perfect sense. In that case this becomes a dependency of #196.

Of course, then we have the question as to whether we want to have both the `postMessage(data, { transfer })` and `postMessage(data, transfer)` variants. Although I'd consider the latter somewhat-legacy, similar to the three-argument version, it seems less bad than the three-argument version does. Hmm...
