### ISSUE TITLE
Feature Request: preview image meta tag

### ISSUE THREAD

**Issue by achung89** [WICG/portals#224]
Dynamically getting preview images for third party navigation is hard to implement, current solutions are complex (html parsers, scrapers) would be nice to be able to indicate a preview image to the portal. 

ex.
`<meta property="portal:image" content="/path/to/image.jpg" />`

**Comment by jakearchibald** [comment]
Currently a portal will render the target document itself. Are you suggesting that `<meta property="portal:image" content="/path/to/image.jpg" />` changes that behaviour and instead renders the image instead?

**Comment by achung89** [comment]
The preview image would be a thumbnail, so the image would be displayed before .activate() is called. 

The meta tag would be located in the head of the document being portaled. The portal can choose to show the thumbnail using a flag. Not 100% sure what the best api would be, but maybe a "preview" attribute on the portal element can indicate to the host  to render the image.  

ex. 
```html
// target document
<meta property="portal:image" content="/path/to/image.jpg" />

// host document
<portal src="..." preview="default" /> // renders target document before activation
<portal src="..." preview="portal:image"  /> // renders /path/to/image.jpg before activation
<portal src="..." preview="portal:image" fallback="/path/to/fallback.jpg" /> // renders /path/to/image.jpg before activation, if image doesn't exist, render fallback image
```

This idea is similar to that of facebook and twitter's og:image and twitter:card. A site can  implement an og:image/twitter:card meta tag to tell facebook/twitter to display a thumbnail when someone shares their site. Facebook uses a scraper to collect the og:image. With the portal element there is opportunity for a developer to implement dynamic thumbnails without a scraper.

by the way, I'm a big fan of http203, it has helped me a ton to understand the browser better

**Comment by jakearchibald** [comment]
I think this is already covered.

If the page containing the portal wants to show a thumbnail instead, it can just use an `<img>` instead (and call activate on a hidden portal).

If the portaled page wants to show a thumbnail instead, it can detect it's in a portal (using `window.portalHost`) and modify its DOM to display an image instead.

**Comment by achung89** [comment]
ah! good point didn't think of that. I'll go ahead and close this issue
