### ISSUE TITLE
Reconsider X-F-O and CSP frame-ancestors restrictions in light of opt-in

### ISSUE THREAD

**Issue by domenic** [WICG/portals#232]
As discussed internally a good amount, and surfaced into the explainer in https://github.com/WICG/portals/pull/231, portaled content will need to opt-in to being portaled.

I believe this should allow us to remove the need to support `X-Frame-Options` and CSP's `frame-ancestors` opt-outs, as portals no longer becomes a way to embed content that might not want to be embeddable. This allows those two controls to stick to controlling frames, and not awkwardly also control portals, which was already a mismatch (e.g. there are definitely sites that don't want to be framed but do want to be portaled; maybe also vice-versa).

**Comment by jakearchibald** [comment]
There's a little mismatch here. `X-Frame-Options: DENY` is the most popular option, due to the legacy issues with `SAMEORIGIN`. Will that also block same-origin portals? Are we requiring an opt-in for same-origin portals?

**Comment by jeremyroman** [comment]
I think `X-Frame-Options: DENY` does block same-origin portal embedding, and semantically that kinda is what they're asking for. I don't know what these legacy issues are, but couldn't authors change to `X-Frame-Options: SAMEORIGIN` or `Content-Security-Policy: frame-ancestors 'self'`?

**Comment by jakearchibald** [comment]
Older browsers didn't check check all ancestors were same origin when using `X-Frame-Options: SAMEORIGIN`. I'm not sure if it's still a problem today (IE, maybe?).
