### ISSUE TITLE
Sandboxed features

### ISSUE THREAD

**Issue by domenic** [WICG/portals#237]
For iframes, HTML defines a number of sandboxing flags, set via the `<iframe>` `sandbox=""` attribute. Most of these are controlled via corresponding keywords (like `allow-popups`), although some are not controllable and show up whenever you use `sandbox=""`.

For portals, I think we generally don't want to copy `sandbox=""`'s design, but instead impose restrictions through document policy. Document policy has a better model in that it doesn't allow the embedder to unilaterally interfere with the operation of the embedded content. This is especially important post-activation; once the portal is activated, the content should not be restricted by what is effectively its "referrer". Consider activating a page then navigating to a totally new one; it'd be bad if the top-level browsing context you were navigating was impacted by the host browsing context several steps ago.

Nevertheless, auditing the sandbox flags reveals some interesting things for portals:

<details>
<summary>Audit details</summary>

- sandboxed navigation browsing context flag: does not apply. Portals have no sync access to other documents so cannot navigate them.

- `allow-popups`: does not apply. Already prohibited pre-activation, and we don't want to allow the embedder to restrict post-activation.

- `allow-top-navigation` and its `-by-user-activation` variant: does not apply. Portals have no access to the top document (well, they are their own top document) and cannot navigate it.

- sandboxed plugins browsing context flag: we could disallow plugins in portaled content for kicks?

- `allow-same-origin`: use cases do not apply, I am pretty sure?

- `allow-forms`: not sure what the use case is for this. Could be valuable?

- `allow-pointer-lock`: well, this should probably be disabled in pre-activation portals anyway. I guess it predates both permission policy and the permissions API, so it used `sandbox=""` for disabling, or something?

- `allow-scripts` + sandboxed automatic features browsing context flag (controls autoplay/autofocus): not sure. Could be valuable?

- sandboxed `document.domain` browsing context flag: we could disable `document.domain` in portals for kicks?

- `allow-popups-to-escape-sandbox`: this is a meta-flag and probably not applicable, unless we lift the actual `sandbox=""` API

- `allow-modals`: we should probably disable modals inside pre-activation portals anyway.

- `allow-orientation-lock`: seems similar to `allow-pointer-lock`.

- `allow-presentation`: seems similar to `allow-pointer-lock`.

- `allow-downloads`: seems similar to `allow-pointer-lock`.

</details>

Proposal:

- We disable pointer lock, orientation lock, the presentation API, downloads, and modals (alert/confirm/prompt/print) pre-activation.
	- These do not seem to have been caught by https://github.com/WICG/portals/commit/5154fc6c4c5bb863f318d4f9b7172e392fbc46b0's use of the permissions API + permissions policy to turn off a bunch of stuff pre-activation.
	- At the spec level, we could do this by reusing the sandboxing flags infrastructure, although that would require mutating the sandboxing flag set post-activation, which I believe would be novel. So maybe we should instead just modify the relevant specs directly to add a pre-activation portal check.
- If we want to add controls for preventing form submission, plugin usage, scripting, document.domain, or autoplay/autofocus, we use document policy for that.
	- I wanted to turn off plugins unconditionally, but I realized then you could not portal a PDF, or navigate a portaled page to a PDF.
	- What if we want to turn these off pre-activation, but allow them post-activation? @jbroman's contention is that document policy is not good for things that vary along this axis.

**Comment by jeremyroman** [comment]
nit: I'm @jeremyroman on GitHub. 😄  Also, @a4sriniv since this is related to permissions stuff.

The sandboxed flags infrastructure is kind of weird because making a sandboxed unique origin makes little sense for a page that will later be activated (what would the address bar even show?). It was my understanding that these were moving to sit atop permissions policy, which seems likely to be the right integration point.

It seems to me to make sense to allow for some sort of hook in the permissions policy algorithms to deny due to portals, and then using that to block pointer lock, orientation lock, etc.

I guess I'm not certain of how turning off things like form submission or scripting would work. You can't today say "I'll navigate to this page, but it can't run scripts", which is why I think it seems kind of weird. Once activation occurs, the brokenness will look to be the fault of the destination site, so doing it unilaterally would be strange. Doing it bilaterally (with Sec-Required-Document-Policy) could be done, but is it useful -- especially useful enough to do now as opposed to leave for later? If the referrer chooses to use such a policy (bilaterally), it also confines the universe of things it can embed to those things which are able to accept that policy. Like `<iframe>`, that may be fine for some use cases, but do we anticipate it being important for the key use cases we want cross-origin `<portal>` for?

**Comment by domenic** [comment]
> It was my understanding that these were moving to sit atop permissions policy, which seems likely to be the right integration point.

I think that would be ideal, much like how it would be ideal if all of the permissions API stuff moved to sit on top of permissions policy. However, I'm not sure whether we want to block on that. It's been contemplated for [a long time](https://github.com/w3c/webappsec-permissions-policy/blob/master/sandbox.md) with not much movement.

> Once activation occurs, the brokenness will look to be the fault of the destination site, so doing it unilaterally would be strange.

Agreed. And I think generally unilateral turning off of features is seen as a legacy mistake.

> Doing it bilaterally (with Sec-Required-Document-Policy) could be done, but is it useful -- especially useful enough to do now as opposed to leave for later?

I'm not sure how useful it is. I guess turning off scripting might be useful as a proxy for "don't use up too many CPU resources". But that would be something that would ideally be lifted after activation, so the bilateral turning-off mechanism wouldn't work so well as-is, since document policy is immutable.

I certainly think we could leave it for later. That was my intention by saying "if we wanted to add controls, we could use document policy": i.e., we could push off this problem onto the document-policy spec, to solve in general for both portals and iframes (and standalone documents, I guess).

**Comment by domenic** [comment]
After #235 we have the following features which are controllable via sandbox, but always enabled in portals:

- form submission
- plugins
- scripting
- `document.domain`
- autofocus (but see #238)

(autoplay is disabled via permissions policy)

My suggestion is that we do not allow embedders to control these for now, in the same way we don't allow embedders to control Document Policy policy items like unsized-images for now.
