### ISSUE TITLE
interactions with window.close

### ISSUE THREAD

**Issue by jeremyroman** [WICG/portals#243]
The spec should specify what happens when `window.close()` is invoked on a portal's window, or while activation is in progress. See https://crbug.com/1110926 for a Chromium bug that arose from this being ill-specified.

**Comment by jakearchibald** [comment]
I think we agreed that this would be a no-op, just as it is from an iframe.

**Comment by jeremyroman** [comment]
Yeah, but we need to actually write down exactly when this applies (e.g., the interval when a context has called `activate` but has not yet been either adopted or unloaded -- this should also be well-defined, IMO, to no-op).

@lucasgadani and I talked about this a little.
