### ISSUE TITLE
Restricted mode with script access

### ISSUE THREAD

**Issue by RByers** [WICG/portals#25]
It's looking like browsers generally will have a frame mode for running script without the ability to read/write storage for tracking protection. We should plan for a third option that is like restricted mode but which doesn't require disabling JS entirely - just network access (ala CSP) and storage access (ala tracking protection).

**Comment by domenic** [comment]
We have a pretty solid plan here now, I think: https://github.com/WICG/portals#privacy-threat-model-and-restrictions
