### ISSUE TITLE
Broken links to web-platform-tests.live

### ISSUE THREAD

**Issue by foolip** [WICG/portals#266]
The first of these is in https://wicg.github.io/portals/#concepts with "(live test)" linking to http://web-platform-tests.live/portals/portal-activate-event.html

I'm not sure where the domain comes from since I can't find it in the source of this repo or Bikeshed, but it's somehow broken and should be wpt.live instead.

**Comment by jeremyroman** [comment]
It looks like this was fixed in Bikeshed a few months ago and we just haven't regenerated since then: https://github.com/tabatkins/bikeshed/commit/7da6fcc72c95c37111d1513d9a0abbd687955363#diff-26d676718d5ed014aef0ade07d3912bc6f6fae5a634051ebe81defa6084b2e5a
