### ISSUE TITLE
Feature request: portal client IDs

### ISSUE THREAD

**Issue by domenic** [WICG/portals#29]
It would be convenient to have the concept of "client ID" (similar to the service worker spec) for portals. In particular, for knowing the ID of a portal you are going to activate, and your predecessor portal.

The particular use case is:

- Outside page (id = 1) activates inside page (id = 2), storing its id ("I just activated 2").
- Inside page activates outside page.
- Outside page checks the ID of its predecessor portal. In this case it ends up being 2, so it knows it's the same as what it originally activated, and can give the appropriate UX treatment.
   - If outside page found the ID of its predecessor portal was not the same, then it is in a novel situation, and probably shouldn't give the same UX.

/cc @dtapuska who can probably explain this a little better than me.

**Comment by dtapuska** [comment]
Ya I was wondering if you cared to know the origin that was activating you. Much like postMessage on Window where you can usually get the source would you ever need to know the URI of the portal you coming from?

Especially if there is a post message context that comes with the portalactivate then you might want to know the source.

**Comment by domenic** [comment]
It seems like if we're wanting to prohibit cross-origin communications channels, this might no longer be as feasible. And, nobody else has chimed in with even a thumbs up over the last 1.5 years. So, I'll close this feature request for now.
