### ISSUE TITLE
Portal Support for <webview>/<x-ms-webview>?

### ISSUE THREAD

**Issue by JonathanRowley** [WICG/portals#32]
Is Portal support planned for Chrome (```<webview>```) Windows (```<x-ms-webview>```) elements?

**Comment by jeremyroman** [comment]
I think that ideally we would make it work for them, too, but I don't know enough about the API they expose to know if there are likely to be complications there. @lucasgadani might have some knowledge about the Chrome side implementation issues. I don't know how much about Microsoft's implementation.

**Comment by kjmcnee** [comment]
Chromium bug: https://crbug.com/942534

**Comment by domenic** [comment]
Closing since this is a Chrome-specific question best tracked in the Chromium bug tracker.
