### ISSUE TITLE
Handle activation when the predecessor is itself a portal browsing context

### ISSUE THREAD

**Issue by lucasgadani** [WICG/portals#53]
When [activating a portal](https://wicg.github.io/portals/#activate-a-portal-browsing-context), if the predecessor browsing context is itself a portal browsing context, the portal host should be replaced so that messages sent to the PortalHost would now reach the predecessor's host.

**Comment by jeremyroman** [comment]
As we discussed elsewhere, the spec now only permits activation if the predeecessor context is not a portal.
