### ISSUE TITLE
Should PortalActivateEvent have ports (or transferred)?

### ISSUE THREAD

**Issue by domenic** [WICG/portals#67]
Unlike MessageEvent in, e.g, https://html.spec.whatwg.org/#window-post-message-steps, it appears that there is no special handling of any MessagePorts in the portalactivate event. Is this a conscious choice? If so, perhaps a quick note should be added explaining why.

Also note https://github.com/whatwg/html/issues/4521 which may further expand the data transferred.

**Comment by jeremyroman** [comment]
It wouldn't be hard to add, but it kinda seems like it'd clutter things up and I'm kinda skeptical of the usefulness of it. (AFAICT it exists from a time before non-ports things could be transferred.)

A "transfer list" value like is proposed in the linked thing seems mildly more useful (albeit mostly for the "I don't know the format of this but want to pass along the same things" use case), but doesn't yet exist on MessageEvent, so we could always add it later if it proves useful there.

**Comment by domenic** [comment]
I still think it's a good idea to add a note explaining why we're inconsistent, so I'll leave this open with a "spec todo" label.
