### ISSUE TITLE
"context object" is going away

### ISSUE THREAD

**Issue by domenic** [WICG/portals#75]
We finally added a first-class notion of "this": https://heycam.github.io/webidl/#this

You can reference it with `<b>this</b>`; first example usage at https://github.com/whatwg/encoding/pull/175. It should flow through everything eventually.

**Comment by jeremyroman** [comment]
Does it deprecate all uses of "context object"? The WebIDL definition of **this** seems to only cover WebIDL operations, getters and setters, but not algorithms ("To **frobnicate a widget _widget_**, run the following steps…").

**Comment by jeremyroman** [comment]
I suspect the answer is "define a variable name at the beginning", so going on that assumption.

**Comment by jeremyroman** [comment]
i.e. assuming the correct for is to write "To **frobnicate a widget *widget*, set *widget*'s frobnication count to 1." instead of "To **frobnicate a widget**, set the context object's frobnication count to 1."

**Comment by domenic** [comment]
Yep, that's exactly the idea :).
