### ISSUE TITLE
Add referrerpolicy="" attribute?

### ISSUE THREAD

**Issue by domenic** [WICG/portals#78]
The spec currently always sets no-referrer, but has a note of

>  Is no-referrer the right referrer policy here, or should we send the document’s URL? 

Is there a reason portals are special, or should we just follow the prevailing pattern for request-creating elements, and add a referrerpolicy="" content attribute which follows [the usual rules](https://html.spec.whatwg.org/#referrer-policy-attribute)?

**Comment by jeremyroman** [comment]
I suppose there isn't really a compelling reason not to follow the usual rules. (It'll take a little bit of plumbing in the implementation, but not too bad.)
