### ISSUE TITLE
Should portals always disown their openers?

### ISSUE THREAD

**Issue by lucasgadani** [WICG/portals#8]
If portals don't [disown](https://html.spec.whatwg.org/#disowned-its-opener) their openers, then we would need to expose the WindowProxy and everything that comes with it across portals, including named access to the Window object and synchronous access to the portal's DOM.

**Comment by KenjiBaheux** [comment]
Would any of the known use cases be negatively impacted by this?

**Comment by lucasgadani** [comment]
It won't affect the cross-origin use cases, but it may affect the design of websites using same-origin seamless navigation and same-origin infinite scroller, though they should still be able to design around an async API (postMessage) instead of a sync API (direct access to the DOM).

**Comment by jeremyroman** [comment]
I'd prefer we ban synchronous access while we still can, unless something comes up that makes it really important to have. It narrows the API surface we have to deal with.

**Comment by lucasgadani** [comment]
I think this is just something to keep around for the spec. The main thing to keep in mind for now is that we don't want to add features that would need synchronous access.

**Comment by jeremyroman** [comment]
AFAIK there is no opener so I think this is resolved. Reopen if you think there's more to do here.
