### ISSUE TITLE
"Whenever a portal element is inserted"

### ISSUE THREAD

**Issue by domenic** [WICG/portals#80]
Portals should probably work in shadow DOM, I think. (Iframes should as well, but apparently aren't specced to do so????).

<del>Portals should probably not work inside non-browsing-context documents, I think.</del> <ins>I see this is already covered by the later steps of the algorithm, so the below is just an editorial suggestion in this regard.</ins>

In that case, you should use https://html.spec.whatwg.org/#becomes-browsing-context-connected

(Same for "removed" steps a bit later.)

Also, there's a "the the" in step 2, and maybe it should cross-reference nested BC.

**Comment by jeremyroman** [comment]
It might be worth fixing this for editorial reasons (it basically lets me factor out the explicit checks, and corrects the handling of non-BC documents), but I think shadow DOM should be fine? Insertion steps run for shadow-inclusive descendants AFAICT.

**Comment by domenic** [comment]
You're right that insertion steps run for shadow-including descendants. I was thinking of "[inserted into a document](https://html.spec.whatwg.org/multipage/infrastructure.html#insert-an-element-into-a-document)".
