### ISSUE TITLE
Adopting into other TLBCs?

### ISSUE THREAD

**Issue by domenic** [WICG/portals#82]
When a portal element is adopted, it gets closed.

This is immediately followed by a note stating

> Since portal elements can have only a guest browsing context while their document belongs to a top-level browsing context, it is impossible to embed a portal browsing context in a nested browsing context. 

It's not clear whether this note is intended to justify the adopting steps, or is just vaguely related.

So, is it intended that adopting a portal element into a different TLBC (e.g., into a portal BC, or into an auxiliary BC) also closes the portal? If so, maybe the note should be tweaked. Something like

> Since portal elements can have only a guest browsing context while their document belongs to a top-level browsing context, it is impossible to embed a portal browsing context in a nested browsing context. We also close the guest browsing context when adopting the portal element into other top-level browsing contexts; developers are required to change and then set back the `src` content attribute to re-trigger a load in such cases.

**Comment by jeremyroman** [comment]
I meant to call out, essentially:
- BC-connected steps imply that you can't make a guest BC if you're in a nested BC
- adopting steps imply that you can't make a guest BC from a TLBC and then move it into the nested BC
- therefore <portal> elements in a nested BC must have a null guest BC (i.e., they don't work)

I'll send a PR with hopefully clearer wording, but I'm sure I'll need to iterate on it more.

The second consequence (that you can move a portal element and then make a new browsing context in its new BC) doesn't seem particularly interesting to me (the author might as well just make a new element).
