### ISSUE TITLE
Is the host abstraction necessary?

### ISSUE THREAD

**Issue by domenic** [WICG/portals#87]
There's a bit of abstraction about the concept of "portal host", which with the current spec doesn't seem to buy that much. Saying that there's a generic portal host concept, which HTMLPortalElement implements, seems to abstract only over "accept a message posted to the host".

Are there plans for future types of hosts that would make this abstraction more worthwhile? Is it just that much cleaner? It's unclear to me, at least.

**Comment by jeremyroman** [comment]
It was an attempt to keep that door open, yeah. One could imagine (and people have asked in general terms) wanting to allow a native application to embed web content in a way that it can smoothly transition into a full Chrome tab, and that the portal abstraction could fit that reasonably neatly.

But I can see how it's be confusing more than helpful at the moment.
