### ISSUE TITLE
Set up PR preview

### ISSUE THREAD

**Issue by domenic** [WICG/portals#92]
https://github.com/tobie/pr-preview/

Apparently all you need to do is add a config file like https://github.com/WICG/kv-storage/blob/master/.pr-preview.json

**Comment by domenic** [comment]
There may have been a more general pr-preview outage that @tobie is looking in to.

**Comment by jeremyroman** [comment]
Yeah, I couldn't figure out what was wrong but it seems to be working now. :man_shrugging:

**Comment by tobie** [comment]
Yes. Fixed it a couple of minutes ago. Sorry for the inconvenience and for not noticing the outage earlier. You'll have to edit the PR body (e.g. by adding a few blank lines to it) to trigger a new build on each PR.
