### ISSUE TITLE
Calling adoptPredecessor() should resolve the activate promise

### ISSUE THREAD

**Issue by a4sriniv** [WICG/portals#97]
Developers can use the promise resolution handler to set an onmessage handler on the now exposed PortalHost object, so any messages sent after calling adoptPredecessor can be handled.

Inside initial host:
```javascript
portal.activate().then(() => {
  window.portalHost.onmessage = e => {
     console.log(e.data); // should log "data"
  }
});
```

Inside initial portal:
```javascript
window.onactivate = e => {
  let portal = e.adoptPredecessor();
  portal.postMessage("data", "*");
}
```

**Comment by jeremyroman** [comment]
I think this was resolved by #126 and I just neglected to close this. Reopen if I'm wrong.
